---
env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-recommended'
parser: 'vue-eslint-parser'
root: true
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: 'module'
plugins:
  - 'vue'
  - '@typescript-eslint'
rules:
  'vue/multi-word-component-names':
    - off
  'vue/max-attributes-per-line':
    - error
    - singleline: 3
  '@typescript-eslint/no-unused-vars':
    - error
  '@typescript-eslint/no-empty-function':
    - off
  no-empty-function:
    - off
  semi:
    - error
    - always
  quotes:
    - error
    - single
    - avoidEscape: true
  comma-dangle:
    - error
    - never
  vue/order-in-components:
    - error
ignorePatterns:
  - 'dist'
  - 'node_modules'
